baseURL = "https://kaj04.github.io/Francesco-Colasurdo-Website/"
languageCode = "en-us"
title = "Francesco Colasurdo"
theme = []

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "cv"
    url = "/cv/"
    weight = 2

  [[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = 3

[params]
  description = "A minimalist, personal portfolio and blog site with an integrated AI assistant."

  # Immagine di sfondo navbar
  navbar_bg_image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeFvJGdRAxe6nT-XO0TwXmb6roe8SewnWt4g&s"
