baseURL = "https://kaj04.github.io/Francesco-Colasurdo-Website/"
languageCode = "it"
title = "Il mio sito"
paginate = 10
theme = "PaperMod"        # indica il tema

[module]                  # usa Hugo Modules per importare il tema
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  defaultTheme = "auto"
  math = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
