baseURL = "https://kaj04.github.io/Francesco-Colasurdo-Website/"
languageCode = "en-us"
title = "Francesco Colasurdo"
theme = []

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "cv"
    url = "/cv/"
    weight = 2
  [[menu.main]]
    name = "blog"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "goals"
    url = "/goals/"
    weight = 4

[params]
  description = "A minimalist, personal portfolio and blog site with an integrated AI assistant."
  
  # Immagini placeholder navbar (sostituisci con i tuoi path in static/assets/)
  navbar_bg_image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeFvJGdRAxe6nT-XO0TwXmb6roe8SewnWt4g&s"