baseURL = "https://kaj04.github.io/Francesco-Colasurdo-Website/"
languageCode = "it"
title = "Il mio sito"
paginate = 10
theme = "PaperMod"

# Importa automaticamente il tema PaperMod (niente submodule da installare)
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  math = true  # abilita KaTeX/LaTeX

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Timeline"
    url = "/timeline/"
    weight = 4
  [[menu.main]]
    name = "Actual Goals"
    url = "/goals/"
    weight = 5

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "monokai"
