baseURL = "https://kaj04.github.io/Francesco-Colasurdo-Website/"
languageCode = "it"
title = "Il mio sito"

# NUOVO: sostituisce 'paginate'
[pagination]
  pagerSize = 10

# IMPORTANTE: usa il path del modulo come tema
theme = ["github.com/adityatelange/hugo-PaperMod"]

# NIENTE blocco [module] qui: non serve se usi 'theme = ["github.com/..."]'

[params]
  defaultTheme = "auto"
  math = true
  mainSections = ["blog"]   # <-- aggiungi questa riga

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[params.homeInfoParams]
  Title = "Ciao, sono Francesco"
  Content = "Qui condivido CV, timeline, obiettivi e riflessioni settimanali."
