baseURL = "https://kaj04.github.io/Francesco-Colasurdo-Website/"
languageCode = "it"
title = "Francesco Colasurdo"

[pagination]
  pagerSize = 10

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

# Uscite: genera SEMPRE anche l'HTML della home, non solo l'RSS
[outputs]
  home = ["HTML", "RSS"]

# Parametri PaperMod
[params]
  defaultTheme = "auto"
  math = true
  mainSections = ["blog"]

  [params.homeInfoParams]
    Title = "Ciao, sono Francesco ðŸ‘‹"
    Content = "CV, timeline, obiettivi e riflessioni settimanali."

  [params.label]
    text = ""            
    icon = "/Francesco-Colasurdo-Website/Logo-Website-Francesco.svg"
    iconHeight = 56      

[markup]
  [markup.goldmark.renderer]
    unsafe = true
    
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    name = "Timeline"
    url = "/timeline/"
    weight = 4

  [[menu.main]]
    name = "Goals"
    url = "/goals/"
    weight = 5

# (facoltativo ma utile in sottocartella)
relativeURLs = true
canonifyURLs = true
